
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xa3-U\xfb\xbbL\x07\x88\x15GC\xd9\xbe\xfd\x870'
    
_lr_action_items = {'RPAREN':([7,9,10,13,],[8,-9,11,-8,]),'STRING':([7,12,],[9,13,]),'COMMA':([9,10,13,],[-9,12,-8,]),'LPAREN':([6,],[7,]),'ID':([0,1,3,4,5,8,11,],[-2,6,-3,-4,-5,-7,-6,]),'$end':([0,1,2,3,4,5,8,11,],[-2,-1,0,-3,-4,-5,-7,-6,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'parameter_list':([7,],[10,]),'compound_statement':([1,],[4,]),'function_call_statement':([1,],[5,]),'program':([0,],[2,]),'statement':([1,],[3,]),'statement_list':([0,],[1,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement_list','program',1,'p_program','lex_yacc.py',124),
  ('statement_list -> <empty>','statement_list',0,'p_statement_list','lex_yacc.py',132),
  ('statement_list -> statement_list statement','statement_list',2,'p_statement_list','lex_yacc.py',133),
  ('statement -> compound_statement','statement',1,'p_statement','lex_yacc.py',143),
  ('compound_statement -> function_call_statement','compound_statement',1,'p_compound_statement','lex_yacc.py',150),
  ('function_call_statement -> ID LPAREN parameter_list RPAREN','function_call_statement',4,'p_function_call_statement','lex_yacc.py',156),
  ('function_call_statement -> ID LPAREN RPAREN','function_call_statement',3,'p_function_call_statement','lex_yacc.py',157),
  ('parameter_list -> parameter_list COMMA STRING','parameter_list',3,'p_parameter_list','lex_yacc.py',167),
  ('parameter_list -> STRING','parameter_list',1,'p_parameter_list','lex_yacc.py',168),
]
